#page title
page_title                                : ProjectX 🖥️                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : vn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : https://cdn.dribbble.com/userupload/4669721/file/original-6a210d77ef118b37f659b83858cfb01c.png?compress=1&resize=2048x1490                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ProjectX 🖥️                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Coming soon 👀                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : See you @ 21:21 April 27th 2023 🙌🏻

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Anonymous 😎                              
your_link                                 : https://m.me/hoanglight.98                     
your_city                                 : HCMC, Vietnam                              
email_address                             : 
facebook_username                         : hoanglight.98                             
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Coming soon 🍷
    description                           : Coming soon
    fontawesome_icon_name                 : gift
  - title                                 : Coming soon 🍷
    description                           : Coming soon
    fontawesome_icon_name                 : gift
  - title                                 : Coming soon 🍷
    description                           : Coming soon
    fontawesome_icon_name                 : gift
  - title                                 : Coming soon 🍷
    description                           : Coming soon
    fontawesome_icon_name                 : gift
  - title                                 : Coming soon 🍷
    description                           : Coming soon
    fontawesome_icon_name                 : gift
  - title                                 : Coming soon 🍷
    description                           : Coming soon
    fontawesome_icon_name                 : gift

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.2
topbar_title_color                        : "#ffffff"

cover_image                               : https://cdn.dribbble.com/userupload/5818576/file/original-a5cac3aecb2d627bb1f54f05df8f98ea.png?compress=1&resize=752x                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#343536"
cover_overlay_transparency                : 0.6

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#328164"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#328164"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
