#-------------------------------
# General Site Settings
title: Wilson D. - thedangw
logo: '/images/logo.png' # You can add own logo. For example '/images/logo.png'.
description: Hi, mình là Hoàng Đăng \ Wilson. Mình thích công nghệ, du lịch và chém gió với bạn bè. Hiện tại mình đang làm Quản lý, Phát triển sản phẩm - Product Management ở Sài Gòn. Blog này là nơi mình viết những thứ linh tinh về cuộc sống & công việc. Hy vọng có thể cùng anh em `chill` thật lâu. Thanks for your interest. Uppp. 🦾
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://www.thedangw.com" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  avatar: '/images/avatar.jpeg'
  name: Hoàng Đăng / Wilson
  job: Product-lover @ HCMC, Vietnam

social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
# - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com/wilson.chillinthe___"}
- {icon: "ion-logo-tumblr", link: "https://t.me/wilsontdw"}
- {icon: "ion-logo-google", link: "mailto:hoangdang.ux@gmail.com"}
# - {icon: "ion ion-logo-github", link: "https://github.com"}  <ion-icon name="chatbubbles"></ion-icon>

# Example of adding a new link to the author section and footer - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Featured Slider
slider: true # NOTE - By default, the slider is set to display featured posts. To add featured post to the slider, add the field, featured: true in the YAML front matter block. If you do not want to use the slider, leave the slider field empty.


#-------------------------------
# Contact Settings
contact:
  email: wilson.citb@gmail.com # Add your email for contact form
  description: Nếu cần trao đổi về công việc quản lý, phát triển sản phẩm - Product Management & thiết kế trải nghiệm người dùng - User Experience Design... hay thậm chí là chém gió, anh em có thể email hoặc nhắn tin cho mình qua Telegram. Contact mình đặt ở Home & cuối trang. Ngoài ra, anh em cũng có thể để gửi mess cho mình ngay tại đây, nhưng mà mách nhỏ một tip là nhắn tin qua Telegram mình sẽ phản hồi nhanh hơn một chút. # Add a description of your form

# NOTE
# Bonso comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: thedangw # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: UA-196301539-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-text: Input nhẹ email ở đây & nhấn `Subscribe` để nhận được thông báo về những bài viết mới của mình trong tương lai nhé. # Add your description.
mailchimp-identifier: wilsonchiller # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
